if(${CMAKE_Fortran_COMPILER_ID} MATCHES "Intel")
  set(CMAKE_Fortran_FLAGS_INIT "-extend-source -warn truncated_source")
elseif(${CMAKE_Fortran_COMPILER_ID} MATCHES "GNU")
  set(CMAKE_C_FLAGS_INIT "-std=c99 -Werror=format")
  set(CMAKE_Fortran_FLAGS_INIT "-ffree-line-length-none")
endif()
if(ENABLE_CUDA)
  set(CMAKE_CUDA_FLAGS_INIT "-dc -arch=compute_70 -code=sm_70")
endif()